version: '3'

services:
  kafka:
    image: apache/kafka:3.7.0
    hostname: kafka
    container_name: mykafka
    ports:
      - "9092:9092"

#  kafka-create-topics:
#    image: apache/kafka:3.7.0
#    depends_on:
#      - kafka
#    hostname: kafka-create-topics
#    command: ["bash", "./create-topics.sh"]
#    working_dir: /scripts
#    volumes:
#      - ./scripts:/scripts